var map;
var labelCount = 1;
var drawingManager = null;
var labelMarkers = [];
var labelBoxes = [];
var overlaysArray = []; // stores overlay objects generated by user

function initialize() {
    var mapOptions = {
        //center: new google.maps.LatLng(63.549, -12.305),
        center: new google.maps.LatLng(27.527758206861883, -29.70703125),
        zoom: 3
    };

    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    drawingManager = new google.maps.drawing.DrawingManager();
    setDrawingOptions();

    google.maps.event.addListener(drawingManager, 'overlaycomplete', drawingFinished);

    drawingManager.setMap(map);
}

function drawingFinished(e) {

    var type = e.type;
    var pos = e.overlay.position;
    overlaysArray.push({
        id: labelCount,
        type: type,
        obj: e.overlay
    });

    // get index position of overlay in array
    var idx = overlaysArray.length - 1;
    var overlayInfo = overlaysArray[idx];

    // markers are easily labelled, shapes require extra effort
    if (type !== "marker") {
        labelShape(overlayInfo);
    }

    // create a button for the overlay
    var outputPane = document.getElementById("code-canvas");
    document.getElementById("leftDiv").innerHTML += "<button id='btnResult' class='result-button'" + idx + " onclick='getOverlayCode(" + idx + ")'>" + overlayInfo.id + "</button>"

    setDrawingOptions(++labelCount);
}

function setDrawingOptions() {

    drawingManager.setOptions({
        //drawingMode: google.maps.drawing.OverlayType.MARKER,
        map: map,
        drawingControl: true,
        drawingControlOptions: {
            position: google.maps.ControlPosition.TOP_CENTER,
            drawingModes: ['marker', 'circle', 'polygon', 'polyline', 'rectangle']
        },

        markerOptions: {
            label: labelCount.toString()
        },
        circleOptions: {
            // add a label
        }
    });
}

function getOverlayCode(idx) {
    document.getElementById("code-area").innerHTML = "";

    switch (overlaysArray[idx].type) {
        case "marker":
            createMarkerCode(overlaysArray[idx].obj);
            break;
        case "circle":
            createCircleCode(overlaysArray[idx].obj);
            break;
        case "polygon":
            createPolygonCode(overlaysArray[idx].obj);
            break;
        case "polyline":
            createPolylineCode(overlaysArray[idx].obj);
            break;
        case "rectangle":
            createRectangleCode(overlaysArray[idx].obj);
            break;
    }
}

function createMarkerCode(marker) {
    console.log(marker);
    var str = "new google.maps.Marker({\n";
    str += "\tposition: new google.maps.LatLng(" + marker.getPosition().lat() + "," + marker.getPosition().lng() + "),\n";
    str += "\tmap: map\n";
    str += "});";
    console.log(str);
    document.getElementById("code-area").innerHTML = str;
}

function createCircleCode(circle) {
    console.log(circle);
    var str = "new google.maps.Circle({\n";
    str += "\tcenter: new google.maps.LatLng(" + circle.getCenter().lat() + "," + circle.getCenter().lng() + "),\n";
    str += "\tradius: " + circle.getRadius() + ",\n";
    str += "\tmap: map\n";
    str += "});";
    console.log(str);
    document.getElementById("code-area").innerHTML = str;
}

function createPolygonCode(poly) {
    console.log(poly);

    // need this because returned path is a MVCArray, not just a vanilla array
    var str = getPathArray("polyPath", poly);
    str += "];\n\n"

    str += "new google.maps.Polygon({\n";
    str += "\tpath: polyPath,\n";
    str += "\tmap: map\n";
    str += "});";
    console.log(str);
    document.getElementById("code-area").innerHTML = str;
}

function createPolylineCode(line) {
    console.log(line);

    // need this because returned path is a MVCArray, not just a vanilla array
    var str = getPathArray("polyLinePath", line);
    str += "];\n\n"

    str += "new google.maps.Polyline({\n";
    str += "\tpath: polyLinePath,\n";
    str += "\tmap: map\n";
    str += "});";
    console.log(str);
    document.getElementById("code-area").innerHTML = str;
}

function createRectangleCode(rect) {
    console.log(rect);

    var rectBounds = "[" + rect.getBounds().toString() + "]";
    console.log(rectBounds)

    var str = "var rectBounds = new google.maps.LatLngBounds(new google.maps.LatLng" + rect.getBounds().getSouthWest() + ", ";
    str += "new google.maps.LatLng" + rect.getBounds().getNorthEast() + ");\n\n";

    str += "new google.maps.Rectangle({\n";
    str += "\tbounds: rectBounds,\n";
    str += "\tmap: map\n";
    str += "});";

    console.log(str);
    document.getElementById("code-area").innerHTML = str;

}

function getPathArray(varname, obj) {
    var path = obj.getPath();
    var str = "[\n";
    path.getArray().forEach(function (value, index, array_x) {
        str += "\t{lat: " + value.lat() + ", lng: " + value.lng() + "}";
        if (index !== (array_x.length - 1)) {
            str += ",\n";
        } else {
            str += "\n";
        }
    });
    return "var " + varname + " = " + str;
}

function getShapeCenter(shape, type) {

    var bounds = new google.maps.LatLngBounds();
    var pathArray = shape.getPath().getArray();

    pathArray.forEach(function (value, index, array_x) {
        bounds.extend(pathArray[index]);
    });

    return bounds.getCenter();

}


function labelShape(overlayInfo) {

    var centerPt = null;
    var overlay = overlayInfo.obj;
    var type = overlayInfo.type;

    // get center
    switch (overlayInfo.type) {
        case "circle":
            centerPt = overlay.getCenter();
            break;
        case "polygon":
            centerPt = getShapeCenter(overlay, type);
            break;
        case "rectangle":
            centerPt = overlay.getBounds().getCenter();
            break;
        case "polyline":
            centerPt = getShapeCenter(overlay, type);
            break;

    }

    var centerMarker = new google.maps.Marker({
        position: centerPt,
        map: map
    });
    overlay.bindTo('center', centerMarker, 'position');
    centerMarker.setVisible(false);

    // keep track of all these markers so we can clear them
    labelMarkers.push(centerMarker);

    // create infobox options
    var labelOptions = {
        content: labelCount.toString(),
        boxStyle: {
            border: "none",
            textAlign: "center",
            fontSize: "14pt",
            width: "50px"
        },
        disableAutoPan: true,
        //pixelOffset: new google.maps.Size(-25, -5),
        pixelOffset: new google.maps.Size(-20, -10),
        position: centerMarker.position,
        closeBoxURL: "",
        isHidden: false,
        pane: "floatPane",
        enableEventPropagation: true
    };
    var ibLabel = new InfoBox(labelOptions);
    ibLabel.open(map, centerMarker);

    // keep track of all these info boxes so we can clear them
    labelBoxes.push(ibLabel);

}

function reset() {
    deleteOverlays();
    clearResultButtons();
    labelCount = 1;
    document.getElementById("code-area").innerHTML = "";
    setDrawingOptions(labelCount);
}

function deleteOverlays() {
    while (overlaysArray[0]) {
        overlaysArray.pop().obj.setMap(null);
    }
    while (labelMarkers[0]) {
        labelMarkers.pop().setMap(null);
    }
    while (labelBoxes[0]) {
        labelBoxes.pop().close();
    }


}

function clearResultButtons() {
    var buttons = document.getElementsByClassName('result-button');

    while (buttons[0]) {
        buttons[0].parentNode.removeChild(buttons[0]);
    }
}

google.maps.event.addDomListener(window, 'load', initialize);